### ISSUE TITLE
hi

### ISSUE THREAD

**Issue by XtremePlayzCODE** [SharkFinPro/SharkFinPro.github.io#1]
hi thx for banning me on sfp, your really missing out on my coding skills lol. can i plz have invite, i don't care what ranks i get just plz let me get atleast 1 person to join red

**Comment by SharkFinPro** [comment]
-_-

**Comment by SharkFinPro** [comment]
you broke tini btw

**Comment by XtremePlayzCODE** [comment]
oh

**Comment by XtremePlayzCODE** [comment]
so i aint helping u with diep

**Comment by SharkFinPro** [comment]
ik
